baseurl = "/"
title = "LearnGo"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = false
    #headline = "chmod + x"
    #description = "My description"
    github = "https://github.com/ChaudhariPrasad"
    twitter = "https://twitter.com/_prasadc_"
    email = "prsdchaudhari@gmail.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"

[menu]
  [[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
  [[menu.main]]
    name = "Categories"
    url = "/categories/"
    weight = 4